kalimat = input("Masukkan kalimat: ").strip()
print("Uppercase:", kalimat.upper())
print("Lowercase:", kalimat.lower())
print("Title:", kalimat.title())
kata = kalimat.split()
print("Jumlah kata:", len(kata))
print("Balik kalimat:", kalimat[::-1])
kata_ganti = input("Kata yang ingin diganti: ")
kata_baru = input("Ganti dengan: ")
print("Hasil:", kalimat.replace(kata_ganti, kata_baru))
